# Generated by Django 4.1.5 on 2023-01-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('father_name', models.TextField(max_length=100)),
                ('contact', models.SmallIntegerField(max_length=13)),
            ],
        ),
    ]
